use ammonia::Builder;
use maplit::{hashmap, hashset};

use crate::theming::{renderer::Renderer, theme::Theme};

#[derive(Eq, PartialEq)]
pub struct Html {
    content: String,
    css_from_theme: String,
}

impl From<String> for Html {
    fn from(value: String) -> Self {
        Html {
            content: value,
            css_from_theme: String::default(),
        }
    }
}

impl Html {
    /// Get a safe HTML version by running ammonia default cleaner with the exception of allow the
    /// class attribute on <code> and <span>, and without cleaning the CSS from the Theme
    pub fn to_safe_html_string(&self) -> String {
        // NOTE: update SECURITY.md if the rules need to change
        let mut cleaner = Builder::default();
        let authorized_tags_attribute = hashmap! {
            "code" => hashset!{"class"}, // authorize the class attribute for <code> because we need to keep highlight names CSS classes
            "span" => hashset!{"class"} // same as for <code>
        };
        cleaner.tag_attributes(authorized_tags_attribute);
        format!(
            "{}{}",
            self.css_from_theme,
            &cleaner.clean(&self.content).to_string()
        )
    }

    /// Push the style generated by a given Theme, this style will not be cleaned !
    pub fn push_style_from_theme(&mut self, theme: &Theme) {
        let renderer = Renderer::new(theme);
        let css = renderer.css();
        self.css_from_theme = format!("<style>{css}</style>\n\n")
    }
}

/// A component that will be able to preview a given document into HTML
pub trait Previewable {
    fn to_html(&self, source: &str) -> Html;
}
