use std::borrow::Cow;
use std::path::PathBuf;

use crate::preview::preview::Html;
use crate::preview::{comrak::HEADER_IDS_SECURITY_PREFIX, preview::ImageUrlRewriteMode};
use ammonia::{Builder, UrlRelativeEvaluate};
use maplit::hashset;
impl Html {
    pub(crate) fn build_html_sanitizer(&self) -> Builder<'_> {
        // NOTE: update SECURITY.md if the rules need to change
        let mut cleaner = Builder::default();
        // Make sure to allow header IDs generated by Comrak, those that have a
        // HEADER_IDS_SECURITY_PREFIX, but reject the other IDs.

        cleaner.add_tag_attributes("a", &["id"]);
        cleaner.add_tag_attributes("code", &["class"]); // authorize the class attribute for <code> because we need to keep highlight names CSS classes
        cleaner.add_tag_attributes("span", &["class"]); // same as for <code>
        cleaner.add_tag_attributes("img", &["src"]);
        // Allow inline SVG, to allow math expressions to be rendered
        // The list of tags has been defined by hand by looking at the minimum for math equations.
        // Some of them might be missing.
        // See https://developer.salesforce.com/docs/platform/lightning-components-security/guide/lws-sanitize-svg.html
        cleaner.add_tag_attributes("p", ["class"]); // to allow the <p class="math-block">
        cleaner.add_tags(["svg", "g", "use", "path", "defs", "symbol"]);
        cleaner.add_tag_attributes(
            "svg",
            [
                "xmlns", // this include xmlns:xlink
                "xlink", "id", "class", "style", "width", "height", "viewBox",
            ],
        );
        cleaner.add_tag_attributes("g", ["class", "transform"]);
        cleaner.add_tag_attributes(
            "use",
            [
                "xlink:href",
                "xlink",
                "href",
                "class",
                "transform",
                "x",
                "y",
                // We do not include them because it seems to have always the default black value for now...
                // "fill",
                // "fill-rule",
            ],
        ); // TODO: make sure xlink:href can be safe ?
           // <path fill="none" stroke="#000" stroke-width=".528" d="M0 1.067h6.292" class="typst-shape"></path>
           //"fill" are removed for same reasons as <use>.
           // But stroke is kept because fraction bar needs to be filled in black, otherwise it is invisible
        cleaner.add_tag_attributes("path", ["d", "class", "stroke-width", "stroke"]);
        cleaner.add_tag_attributes("defs", ["id"]);
        cleaner.add_tag_attributes("symbol", ["id", "overflow"]);

        // Allow iframe to allow integration of Youtube videos
        // <iframe width="560" height="315" src="https://www.youtube.com/embed/X8jsijhllIA?si=yKfZDBbWHfLTky2D" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        cleaner.add_tags(["iframe", "video"]);
        // Note: for let's block width and height because it doesn't adapt to mobile screen...
        cleaner.add_tag_attributes("iframe", ["src", "title", "allowfullscreen"]);

        // Allow video tag
        // <video src="https://player.vimeo.com/progressive_redirect/playback/1049055406/rendition/1080p/file.mp4?loc=external&oauth2_token_id=1788610641&signature=1695f267dbd74c77f96ae5f1da6d0c389634b78de8973b81f69a503b596a3c4e" height="900" controls="true"></video>
        cleaner.add_tag_attributes("video", ["controls", "width", "src"]); // do not allow height to avoid fixing a too high video

        cleaner.strip_comments(true);

        // Note: this is only applied to authorized tags (defaults and those above). If we remove
        // the line cleaner.add_tag_attributes("a", &["id"]); it seems to not be called.
        cleaner.attribute_filter(|_, attribute, value| {
            if attribute != "id" {
                Some(value.into())
            } else {
                // Note: "prefix" is the default prefix used by oxvg_optimiser
                if value.starts_with(HEADER_IDS_SECURITY_PREFIX) || value.starts_with("prefix") {
                    Some(value.into())
                } else {
                    None // ban other IDs without a security prefix, this is probably user generated HTML
                }
            }
        });
        cleaner
    }

    // Note: This is actually not about security but more about making URLs transformation to allow images to be visible
    pub(crate) fn setup_image_urls_rewrite(&self, cleaner: &mut Builder) {
        // Rewrite the image URLs with a prefix if provided, to adapt to the platform (web needs
        // sometimes a subfolder for images, desktop app needs an absolute path prefix, ...)
        match &self.image_rewrite {
            ImageUrlRewriteMode::None => {}
            ImageUrlRewriteMode::SimplePrefixed(prefix) => {
                struct PurePrefix {
                    prefix: String,
                }
                impl<'a> UrlRelativeEvaluate<'a> for PurePrefix {
                    fn evaluate<'url>(&self, url: &'url str) -> Option<Cow<'url, str>> {
                        // If we have an anchor, we don't want to touch it, because it doesn't need any prefix.
                        // In case of <use href="#abc" > we don't want touch this value.
                        if url.trim().starts_with("#") {
                            Some(Cow::Borrowed(url))
                        } else {
                            let mut copy = self.prefix.clone();
                            copy.push_str(url);
                            Some(Cow::Owned(copy))
                        }
                    }
                }
                cleaner.url_relative(ammonia::UrlRelative::Custom(Box::new(PurePrefix {
                    prefix: prefix.to_owned(),
                })));
            }
            ImageUrlRewriteMode::TauriFullPath(path) => {
                let new_url_schemes = hashset!["asset"];
                cleaner.add_url_schemes(new_url_schemes);

                cleaner.url_relative(ammonia::UrlRelative::Custom(Box::new(TauriPathRewriter {
                    path: path.to_owned(),
                })));
            }
        }
    }
}

struct TauriPathRewriter {
    path: String,
}

/// This is just a reimplementation of Tauri's JavaScript function convertFileSrc()
/// to have a safe Rust only HTML generation without any JavaScript HTML manipulation
/// https://v2.tauri.app/fr/reference/javascript/api/namespacecore/#convertfilesrc
///
/// See implementation to better understand why the tauri_prefix
/// https://github.com/tauri-apps/tauri/blob/18464d9481f4d522c305f21b38be4b906ab41bd5/crates/tauri/scripts/core.js#L13
impl<'a> UrlRelativeEvaluate<'a> for TauriPathRewriter {
    fn evaluate<'url>(&self, url: &'url str) -> Option<std::borrow::Cow<'url, str>> {
        // If we have an anchor, we don't want to touch it, because it doesn't need any prefix.
        // In case of <use href="#abc" > we don't want touch this value.
        if url.trim().starts_with("#") {
            Some(Cow::Borrowed(url))
        } else {
            #[cfg(target_os = "windows")]
            let tauri_prefix = "http://asset.localhost/";
            #[cfg(target_os = "android")]
            let tauri_prefix = "http://asset.localhost/";
            #[cfg(target_os = "linux")]
            let tauri_prefix = "asset://localhost/";
            #[cfg(target_os = "macos")]
            let tauri_prefix = "asset://localhost/";

            let absolute_path = PathBuf::from(&self.path)
                .join(url)
                .into_os_string()
                .to_string_lossy()
                .to_string();
            let encoded_absolute_path = urlencoding::encode(&absolute_path);
            let result = format!("{tauri_prefix}{encoded_absolute_path}");
            Some(Cow::Owned(result))
        }
    }
}
