[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
colored = "3.0.0"
dme-core = { path = "../" }
once_cell = "1.21.3"
serde = "1.0.219"
serde_json = "1.0.140"
