[package]
name = "dme-core"
version = "0.1.0"
description = "The core library of DME, backing up the CLI and Tauri app."
authors = ["you"]
edition = "2021"

# Recommended configuration
# https://tauri.app/concept/size/#cargo-configuration
[profile.dev]
incremental = true # Compile your binary in smaller steps.
[lib]
name = "dme_core"

[dependencies]
etcetera = "0.11.0"
comrak = { version = "0.50.0", default-features = false }
once_cell = "1.21.3"
pretty_assertions = "1.4.1"
regex = "1.11.1"
walkdir = "2"
num_cpus = "1.16"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
thiserror = "2.0.12"
toml = "0.8.23"
nucleo-matcher = "0.3.1"
maplit = "1.0.2"
urlencoding = "2.1.3"
mini-moka = "0.10.3"

# Feature flag "security" sanitizing any generated HTML (for Markdown or code)
ammonia = { version = "4.1.0", default-features = false, optional = true }

# Feature flag "colored-code": Code highlighting with Tree-Sitter and dynamic grammars installation + loading
tree-sitter = { version = "0.26.5", default-features = false, optional = true }
tree-sitter-highlight = { version = "0.26.5", default-features = false, optional = true }
tree-sitter-loader = { version = "0.26.5", optional = true }

# Feature flag "math": Render Markdown math equations with Typst (this fully embed Typst into the final program, with restricted access)
typst = { version = "0.14", default-features = false, optional = true }
typst-svg = { version = "0.14", default-features = false, optional = true }
typst-kit = { version = "0.14.2", default-features = false, features = [
    "embed-fonts",
], optional = true }
# In addition, we need to optimize Typst generated SVG to make them less heavy
oxvg_ast = { version = "0.0.7", default-features = false, features = [
    "parse",
    "roxmltree",
], optional = true }
oxvg_optimiser = { version = "0.0.7", default-features = false, optional = true }

[dev-dependencies]
pretty_assertions = "1.4.1"
rand = "0.10.0"

[features]
default = ["security"]
# This security feature flag is including HTML sanitizing and URLs rewrite (because it also depends on ammonia)
# By default images url rewrite doesn't apply so there is no need to disable this via a feature flag.
# Removing it for compilation speed means we also need to remove the security stuff with ammonia, so it actually
# makes sense to group them here.
security = ["dep:ammonia"]
math = [
    "dep:typst",
    "dep:typst-svg",
    "dep:typst-kit",
    "dep:oxvg_ast",
    "dep:oxvg_optimiser",
]
colored-code = [
    "dep:tree-sitter",
    "dep:tree-sitter-loader",
    "dep:tree-sitter-highlight",
]
